project:
  type: website
  resources:
    - "images/twitter-card.png"

website:
  favicon: images/logo.ico
  title: "SDT"
  site-url: https://cdaresume.com
  description: "An informative platform showcasing diverse projects and insights."

  #repo-url: https://github.com/your-username/your-repo
  #repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@your_twitter_handle"
    image: "/images/twitter-card.png"

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
        menu:
          - text: "R Projects"
            href: r-projects.qmd
          - text: "Python Projects"
            href: python_projects.qmd
          - text: "Other Projects"
            href: other_projects.qmd
      - text: "About"
        href: about.qmd
        
    right:
      - icon: github
        href: https://github.com/cdaR-de/sdt
        aria-label: GitHub repo
      - icon: linkedin
        href: https://www.linkedin.com/in/sidar-deniz-topaloğlu/
        aria-label: Linkedin Profile
      - icon: envelope
        href: "mailto:sidardenizt@gmail.com"
        #href: about.qmd
        aria-label: Email Me

  page-footer:
    right: "Built with ❤️ using [Quarto](https://quarto.org/)"
    left: |
      Proudly supported by
      [![RStudio](images/rstudio-logo-Photoroom.png)](https://www.rstudio.com)
      
format:
  html:
    theme:
      light: [cosmo]
      dark: [darkly]
    css: styles1.css
    toc: true
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

editor: visual
